ALTER TABLE "StaffMember" ADD COLUMN IF NOT EXISTS "facebook" TEXT;
ALTER TABLE "StaffMember" ADD COLUMN IF NOT EXISTS "instagram" TEXT;
ALTER TABLE "StaffMember" ADD COLUMN IF NOT EXISTS "twitter" TEXT;
ALTER TABLE "StaffMember" ADD COLUMN IF NOT EXISTS "linkedin" TEXT;
