-- AlterTable: expand StudentApplication to match official paper form
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "nationality" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "residenceStatus" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "motherTongue" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "previousStudentCode" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "previousStudentCodeYear" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "previousSchoolCode" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "previousSchoolCodeYear" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "previousClassAttended" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "classAppliedFor" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "attendanceType" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "province" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "sector" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "cell" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "village" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "religion" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "fundingSource" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "fatherName" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "fatherAlive" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "fatherPhone" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "fatherId" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "fatherOccupation" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "motherName" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "motherAlive" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "motherPhone" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "motherId" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "motherHomeAddress" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "motherOccupation" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "guardianName" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "guardianPhone" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "guardianEmail" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "guardianHomeAddress" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "guardianOccupation" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "healthMedicalBackground" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "emergencyContactName" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "emergencyContactPhone" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "emergencyContactAddress" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "agreePhotoUse" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "agreeFeesNonRefundable" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "signatureName" TEXT;
ALTER TABLE "StudentApplication" ADD COLUMN IF NOT EXISTS "submittedAtLocation" TEXT DEFAULT 'HUYE';
